name = "Cbc"
uuid = "9961bab8-2fa3-5c5a-9d89-47fab24efd76"
repo = "https://github.com/jump-dev/Cbc.jl.git"
version = "1.0.2"

[deps]
Cbc_jll = "38041ee0-ae04-5750-a4d2-bb4d0d83d27d"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
Cbc_jll = "=2.10.5, ~200.1000.501"
MathOptInterface = "1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
